### ISSUE TITLE
Bunch of Requests

### ISSUE THREAD

**Issue by ghost** [Nazky/PS22PS4-GUI#2]
Here Are a Couple of Requests for the Ps2 Fpkg Creator
Text:
1. Speedhack Sliders
--ee-cycle-scalar= [Between 1.0 and 5.0]
--vu1-mpg-cycles=[Between 100 and 3000]

2. Speedhack Toggles
--vu1-di-bits=0
--vu1-const-prop=1

3. Debug Toggles
--vif1-instant-xfer=0 (Delay vif1)
--vu1=jit-sync (Turn off MTVU)
--fpu-accurate-range=0x1c0000,0x2000000   (Accurate fpu instructions)

LUA:
1. Change Texture Filtering Mode Toggle
These two lua configuration can help fix graphical problems

Mode 1:

apiRequest(0.4)

local emuObj = getEmuObject()

emuObj.SetGsTitleFix( "forceSimpleFetch", "reserved", { texMode=1 } )

Mode 2: 

apiRequest(0.4)

local emuObj = getEmuObject()

emuObj.SetGsTitleFix( "forceSimpleFetch", "reserved", { texMode=2 } )

Also I Would love to request the feature to automatically download game's cover

and Also It would help ALOT if you could add a feature that makes the program only edit changed the configuration in already existing fpkg, Since recreating the fpkg takes a lot of time usually.

**Comment by Nazky** [comment]
if you have a cover database i can add the auto cover download, i am not sure if we can add files to fpkg without unpack and repack again so for it's dead the config but for lua files we can change the path so that can work and for the options request i am going to make a config and lua maker with all the option in a gui format to be easy to modify
